# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c5caa8841848ec93a317d52d5154bea9343e0ec8dd957188182ff7853f949db1195d316c4a8e573f4a4e9682ac8b97ac530a9432b8de0e2aeb1bf46d2c8c626

test:
  secret_key_base: 9c8e08ddc3caf0957e9c19cb27e1e56b5833d9512974669eb56ce650b55c49c7816449486a6a8511936e944c30298d6f0017cfe9b3d55e68923978eaf833561b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
